nameOverride: ""
fullOverride: ""
replicaCount: 2
namespace: reactor-lab

container:
  imagePullSecrets: docker-registry
  image: bradmccoydev/reactor-lab:latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080