{
 "title": "Manly Surf",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "![Basiq Logo](https://avatars.githubusercontent.com/u/18345448?s=400&u=224edbda23a3d782d856e3da94b21e8445a42e08&v=4)\n"
   }
  },
  {
   "title": "Manly Water Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_water_temperature" }
   ]
  },
  {
   "title": "Manly Wave Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_wave_height" }
   ]
  },
  {
   "title": "Manly Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_air_temperature" }
   ]
  },
  {
   "title": "Manly Swell Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_swell_height" }
   ]
  },
  {
   "title": "Manly Cloud Coverage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_cloud_cover" }
   ]
  },
  {
   "title": "Manly Swell Period",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_swell_period" }
   ]
  },
  {
   "title": "Manly Swell Direction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_swell_direction" }
   ]
  },
  {
   "title": "Manly Surf Wave Direction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "surf_wave_direction" }
   ]
  }
 ]
}