apiVersion: batch/v1
kind: CronJob
metadata:
  name: morning-surf-report
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: morning-surf-report
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            command:
            - sendmetrics
            env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: surf-report
                  key: api-token
          restartPolicy: Never
