name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write # needed to write releases
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: latest

      - name: Prepare keys for signing
        env:
          SIGNING_KEY_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY }}
          SIGNING_KEY_PASSPHRASE_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY_PASSPHRASE }}
          KEY_PATH: ".gpg-dir"
          SIGNING_KEY_PATH: ".gpg-dir/secring.gpg"
          SIGNING_KEY_PASSPHRASE_PATH: ".gpg-dir/passphrase"
        run: |
          mkdir "$KEY_PATH"
          base64 -d <<< "$SIGNING_KEY_BASE64" > "$SIGNING_KEY_PATH"
          base64 -d <<< "$SIGNING_KEY_PASSPHRASE_BASE64" > "$SIGNING_KEY_PASSPHRASE_PATH"
          echo "CR_PASSPHRASE_FILE=$SIGNING_KEY_PASSPHRASE_PATH" >> "$GITHUB_ENV"
          echo "CR_KEYRING=$SIGNING_KEY_PATH" >> "$GITHUB_ENV"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        with:
          charts_dir: charts
          config: charts/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
