name: release

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write
  actions: read

jobs:

  build:
    runs-on: ubuntu-22.04

    env:
      IMAGE_NAME: bradmccoydev/surf-report

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
    - uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 # v3.0.5
    - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

    - name: Login to GitHub Container registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      uses: keptn/gh-action-extract-branch-name@main
    
    - name: Prepare
      id: prep
      run: |
        VERSION=sha-${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Get current date and time
      id: get_datetime
      run: |
        DATETIME=$(date +'%Y%m%d%H%M')
        BUILD_TIME=$(date -u "+%F_%T")
        echo "DATETIME=$DATETIME" >> "$GITHUB_OUTPUT"
        echo "BUILD_TIME=$BUILD_TIME" >> "$GITHUB_OUTPUT"

    - name: Generate images meta
      id: meta
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: type=sha,format=long
    
    - name: Build Docker Image
      id: docker_build_image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
      with:
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
            REVISION=${{ steps.prep.outputs.REVISION }}
            GIT_HASH=${{ steps.extract_branch.outputs.GIT_SHA }}
            RELEASE_VERSION=${{ steps.get_datetime.outputs.DATETIME }}
            BUILD_TIME=${{ steps.get_datetime.outputs.BUILD_TIME }}
